name: Package proxy and upload as artifact

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js and yarn
      - name: Install Node.js and package manager
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      
      # Install necessary system dependencies
      - name: yarn install
        run: yarn install

      - name: Minify proxy file
        run: yarn minify

      - uses: actions/upload-artifact@v3
        with:
          name: tanktrouble-proxy-minified
          path: dist/proxy.min.js
          if-no-files-found: error
